main.plugins.home_base.enabled = false
main.plugins.home_base.minimum_signal_strength = -75
main.plugins.home_base.password = 'your_home_network_password'
main.plugins.home_base.ssid = 'your_home_network'
