main.plugins.onlinehashcrack.enabled = true
main.plugins.onlinehashcrack.email = "bauke.molenaar@gmail.com"
main.plugins.onlinehashcrack.dashboard = ""
main.plugins.onlinehashcrack.single_files = true
main.plugins.onlinehashcrack.whitelist = [
 "B33zH1v3!",
 "Downtown-Personeel-2.4G",
 "Downtown-Personeel-5G",
 "Downtown-Gasten",
 "2C:3A:FD:42:88:60",
 "2C:3A:FD:42:88:61",
 "BC:05:43:13:6F:82",
 "DownTown Internet",
]