main.plugins.telegram.bot_name = "WifiKirby_bot"
main.plugins.telegram.bot_token = "6015731659:AAEVVeTsI-S5ZhWgQdz5pSgFZySQd_XvHMw"
main.plugins.telegram.chat_id = "639276511"
main.plugins.telegram.enabled = false
main.plugins.telegram.send_message = true
main.plugins.telegram.send_picture = true
